import { AIClient } from './ai-client.js';
import logger from '../utils/logger.js';

// ═══════════════════════════════════════════════════════════════════
// Tool Creator — Dynamic Tool Generation at Runtime (AGI 2026)
// Creates sandboxed tools from natural language descriptions
// ═══════════════════════════════════════════════════════════════════

/** Definition of a dynamically created tool */
export interface DynamicTool {
  name: string;
  description: string;
  parameters: Record<string, { type: string; description: string; required?: boolean }>;
  implementation: string;   // The source code
  compiledFn: Function;     // Compiled function
  createdAt: number;
  lastUsed: number;
  useCount: number;
}

/** Tool spec generated by AI */
interface ToolSpec {
  name: string;
  description: string;
  parameters: Record<string, { type: string; description: string; required?: boolean }>;
  implementation: string;
}

const MAX_DYNAMIC_TOOLS = 10;

/** Allowed globals in the sandbox */
const SANDBOX_GLOBALS: Record<string, unknown> = {
  fetch: globalThis.fetch,
  JSON,
  Buffer,
  Date,
  Math,
  URL,
  URLSearchParams,
  TextEncoder: globalThis.TextEncoder,
  TextDecoder: globalThis.TextDecoder,
  parseInt,
  parseFloat,
  isNaN,
  isFinite,
  encodeURIComponent,
  decodeURIComponent,
  btoa: globalThis.btoa,
  atob: globalThis.atob,
  console: { log: () => {}, warn: () => {}, error: () => {} },
};

/** Blocked patterns in tool source code */
const BLOCKED_PATTERNS = [
  /require\s*\(/,
  /import\s+/,
  /process\./,
  /child_process/,
  /\beval\b\s*\(/,
  /Function\s*\(/,
  /fs\./,
  /path\./,
  /os\./,
  /net\./,
  /http\./,
  /crypto\./,
  /__dirname/,
  /__filename/,
  /globalThis\./,
  /Deno\./,
  /Bun\./,
  /\.constructor\s*[\[(]/,   // Prevent prototype chain escape
  /\bProxy\b/,
  /\bReflect\b/,
  /\.__proto__/,
  /prototype\s*\[/,
];

/** Rate limit: max tool creations per hour to prevent runaway generation */
const MAX_CREATIONS_PER_HOUR = 5;

export class ToolCreator {
  private ai: AIClient;
  private tools = new Map<string, DynamicTool>();
  private creationTimestamps: number[] = [];

  constructor(ai: AIClient) {
    this.ai = ai;
  }

  /** Create a new tool from natural language description */
  async createTool(description: string): Promise<{ success: boolean; name?: string; error?: string }> {
    // Opt-in only — dynamic tool creation must be explicitly enabled
    if (process.env.DYNAMIC_TOOLS_ENABLED !== 'true') {
      return { success: false, error: 'Dynamic tool creation is disabled. Set DYNAMIC_TOOLS_ENABLED=true to enable.' };
    }

    // Rate limit: prevent runaway tool creation (emergent behavior ceiling)
    const oneHourAgo = Date.now() - 3600_000;
    this.creationTimestamps = this.creationTimestamps.filter(t => t > oneHourAgo);
    if (this.creationTimestamps.length >= MAX_CREATIONS_PER_HOUR) {
      return { success: false, error: `Rate limited: max ${MAX_CREATIONS_PER_HOUR} tool creations per hour` };
    }
    this.creationTimestamps.push(Date.now());
    try {
      // 1. AI generates tool spec
      const specResponse = await this.ai.chat({
        systemPrompt: `You are a tool creation engine. Given a description, generate a JSON tool specification.
The tool implementation must be a pure JavaScript function body (no imports, no require, no filesystem access).
Available in scope: fetch, JSON, Buffer, Date, Math, URL, URLSearchParams, parseInt, parseFloat.
The function receives a single \`params\` object and must return a string result.

Respond ONLY with valid JSON in this exact format:
{
  "name": "tool_name_snake_case",
  "description": "What the tool does",
  "parameters": {
    "param1": { "type": "string", "description": "What param1 is", "required": true }
  },
  "implementation": "const result = ...; return JSON.stringify(result);"
}`,
        messages: [{ role: 'user', content: `Create a tool that: ${description}` }],
        maxTokens: 2000,
        temperature: 0.3,
      });

      // 2. Parse the spec
      const jsonMatch = specResponse.content.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        return { success: false, error: 'AI did not return valid JSON spec' };
      }
      const spec: ToolSpec = JSON.parse(jsonMatch[0]);

      if (!spec.name || !spec.implementation) {
        return { success: false, error: 'Missing name or implementation in spec' };
      }

      // 3. Security check — scan for blocked patterns
      for (const pattern of BLOCKED_PATTERNS) {
        if (pattern.test(spec.implementation)) {
          return { success: false, error: `Blocked pattern detected: ${pattern.source}` };
        }
      }

      // 4. Compile in sandbox
      const compiledFn = this.compileSandboxed(spec.implementation);

      // 5. Test run with empty params
      try {
        const testResult = await Promise.race([
          Promise.resolve(compiledFn({})),
          new Promise((_, reject) => setTimeout(() => reject(new Error('Test execution timed out')), 5000)),
        ]);
        logger.info('Tool test run passed', { name: spec.name, resultType: typeof testResult });
      } catch (testErr: any) {
        // Test failure is OK for tools that require specific params
        logger.debug('Tool test run (expected for param-required tools)', { name: spec.name, error: testErr.message });
      }

      // 6. Evict oldest if at capacity
      if (this.tools.size >= MAX_DYNAMIC_TOOLS) {
        this.evictLRU();
      }

      // 7. Register
      this.tools.set(spec.name, {
        name: spec.name,
        description: spec.description,
        parameters: spec.parameters ?? {},
        implementation: spec.implementation,
        compiledFn,
        createdAt: Date.now(),
        lastUsed: Date.now(),
        useCount: 0,
      });

      logger.info('Dynamic tool created', { name: spec.name, description: spec.description });
      return { success: true, name: spec.name };
    } catch (err: any) {
      logger.warn('Tool creation failed', { error: err.message });
      return { success: false, error: err.message };
    }
  }

  /** Execute a dynamic tool */
  async executeTool(name: string, params: Record<string, unknown>): Promise<string> {
    const tool = this.tools.get(name);
    if (!tool) throw new Error(`Dynamic tool "${name}" not found`);

    tool.lastUsed = Date.now();
    tool.useCount++;

    try {
      const result = await Promise.race([
        Promise.resolve(tool.compiledFn(params)),
        new Promise((_, reject) => setTimeout(() => reject(new Error('Tool execution timed out (10s)')), 10000)),
      ]);
      return typeof result === 'string' ? result : JSON.stringify(result);
    } catch (err: any) {
      throw new Error(`Tool "${name}" execution error: ${err.message}`);
    }
  }

  /** Get a tool by name */
  getTool(name: string): DynamicTool | undefined {
    return this.tools.get(name);
  }

  /** Get all dynamic tool names */
  getToolNames(): string[] {
    return Array.from(this.tools.keys());
  }

  /** Get tool definitions in Anthropic format for AI requests */
  getToolDefinitions(): Array<{
    name: string;
    description: string;
    input_schema: { type: string; properties: Record<string, unknown>; required: string[] };
  }> {
    return Array.from(this.tools.values()).map(t => ({
      name: `dynamic_${t.name}`,
      description: `[Dynamic Tool] ${t.description}`,
      input_schema: {
        type: 'object' as const,
        properties: Object.fromEntries(
          Object.entries(t.parameters).map(([k, v]) => [k, { type: v.type, description: v.description }]),
        ),
        required: Object.entries(t.parameters).filter(([, v]) => v.required).map(([k]) => k),
      },
    }));
  }

  /** Remove a tool */
  removeTool(name: string): boolean {
    const deleted = this.tools.delete(name);
    if (deleted) logger.info('Dynamic tool removed', { name });
    return deleted;
  }

  /** List all tools with metadata */
  listTools(): Array<{ name: string; description: string; useCount: number; createdAt: number }> {
    return Array.from(this.tools.values()).map(t => ({
      name: t.name,
      description: t.description,
      useCount: t.useCount,
      createdAt: t.createdAt,
    }));
  }

  /** Compile implementation in a sandboxed Function */
  private compileSandboxed(code: string): Function {
    // Build a function with only allowed globals
    const globalNames = Object.keys(SANDBOX_GLOBALS);
    const globalValues = Object.values(SANDBOX_GLOBALS);

    // The function receives `params` as argument + sandboxed globals
    const fn = new Function(
      ...globalNames,
      'params',
      `"use strict";\n${code}`,
    );

    // Return a wrapped function that injects the globals
    return (params: Record<string, unknown>) => fn(...globalValues, params);
  }

  /** Evict least recently used tool */
  private evictLRU(): void {
    let oldest: DynamicTool | null = null;
    for (const tool of this.tools.values()) {
      if (!oldest || tool.lastUsed < oldest.lastUsed) {
        oldest = tool;
      }
    }
    if (oldest) {
      this.tools.delete(oldest.name);
      logger.info('Evicted LRU dynamic tool', { name: oldest.name, useCount: oldest.useCount });
    }
  }
}
